"use client";

import { useState } from "react";
import { motion } from "framer-motion";
import { FileText, ChevronDown, ChevronUp, Copy, Check } from "lucide-react";
import { Card, SectionHeader } from "@/components/ui/Card";
import { Button } from "@/components/ui/Button";

interface Props {
  transcript: string;
  onAnalyse: () => void;
  analysing: boolean;
}

export function TranscriptViewer({ transcript, onAnalyse, analysing }: Props) {
  const [expanded, setExpanded] = useState(false);
  const [copied, setCopied] = useState(false);

  const preview = transcript.slice(0, 600);
  const isLong = transcript.length > 600;
  const displayText = expanded || !isLong ? transcript : preview + "…";

  const copyToClipboard = async () => {
    await navigator.clipboard.writeText(transcript);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const wordCount = transcript.split(/\s+/).filter(Boolean).length;
  const charCount = transcript.length;

  return (
    <Card glow>
      <SectionHeader
        icon={<FileText className="w-5 h-5" />}
        title="Speech Transcript"
        subtitle="Generated by Vosk Speech Recognition"
        badge={`${wordCount} words`}
      />

      {/* Stats row */}
      <div className="flex gap-3 mb-4 flex-wrap">
        {[
          { label: "Words", value: wordCount.toLocaleString() },
          { label: "Characters", value: charCount.toLocaleString() },
          {
            label: "Est. Duration",
            value: `~${Math.round(wordCount / 140)} min`,
          },
        ].map(({ label, value }) => (
          <div
            key={label}
            className="flex-1 min-w-[80px] rounded-xl bg-white/5 border border-white/10 px-3 py-2 text-center"
          >
            <p className="text-lg font-bold text-white">{value}</p>
            <p className="text-xs text-slate-400">{label}</p>
          </div>
        ))}
      </div>

      {/* Transcript text */}
      <div className="relative rounded-xl bg-black/30 border border-white/10 p-4 mb-4">
        <button
          onClick={copyToClipboard}
          className="absolute top-3 right-3 p-1.5 rounded-lg bg-white/10 hover:bg-white/20 text-slate-400 hover:text-white transition-colors"
          title="Copy transcript"
        >
          {copied ? <Check className="w-4 h-4 text-green-400" /> : <Copy className="w-4 h-4" />}
        </button>

        <motion.p
          className="text-slate-300 text-sm leading-relaxed whitespace-pre-wrap pr-8"
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          transition={{ duration: 0.5 }}
        >
          {displayText}
        </motion.p>

        {isLong && (
          <button
            onClick={() => setExpanded(!expanded)}
            className="mt-3 flex items-center gap-1 text-xs text-purple-400 hover:text-purple-300 transition-colors font-medium"
          >
            {expanded ? (
              <>
                <ChevronUp className="w-3 h-3" /> Show less
              </>
            ) : (
              <>
                <ChevronDown className="w-3 h-3" /> Show full transcript
              </>
            )}
          </button>
        )}
      </div>

      {/* CTA */}
      <Button
        size="lg"
        className="w-full"
        onClick={onAnalyse}
        loading={analysing}
        icon={
          <span className="text-lg">🧠</span>
        }
      >
        {analysing ? "Analyzing speech with AI models…" : "Analyze Speech"}
      </Button>
    </Card>
  );
}
